language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ufranske
  password:
    secure: EZyNud3iQPN3iwO3JgCFOHJh2AycPVfWKR47nr9Pk4w7ZMGMiiubZI50OHuaL+4u9xHhFmWHDfViMvNrxABnflnAclf6A9bHRsu1t0WRqSoCUkK1o5lLEp2ZzujU6fsZVYxAGQdJpy1VKhsEj9ikcGCCUeqx/MtmE6TYcdLa/HUvkOaUtHNvoQcQ52q/uTfNa3fBBFVX+D7r6v9lIpLTdkUyRK+1nAXURAtz2dZq8Ss3HPa7g34qMmrKQbSPPuHioihG++Tyg4KCg2qEIC8s5MfZoZGTe+6htVr7bDO0GRwmPe3oGsaIeilno3AJx4kpOk+fE8jd2YAm0FnQlIvx9CZP34pGe6+MRirGgaIr67TMbc3Rd8uVtHhkOFE/jysWMVTeV7rr/a9oy2rPidkN7PJ1rCDMmmUBPsm2+xwjNkNC2gP9DjtFX9QfQJfNzzyhTw8rx+Im07nraLUvJADveXyrJ8w2pVQXFqY4PlhO3LHA7QaO0pRuWbYkcOBZ1AXcquKQepj6+aLimyVwOxwH6k6D5CAeCtlsIH3A0Md8ybvYyvKrb1VrAzU/iFQymK/GFTqkyFBwNPsAj63fHsnCuA4LWu02zN6HsAu72kpvc8nTOoAvB+Qi68Y2d3rAQR8sheGBuzTlugz8YbEvr7sIDvnUipevYNG2ebt8FXnZ+Bw=
  on:
    tags: true
    repo: ufranske/jinja2_stringcase
    branch: master
    python: 2.7
