language: python
python:
- 3.6
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ufranske
  password:
    secure: X7LWHT7ZK5PpEZ+CYsTl6FbLwJ4RGXWx9bsDhyPd/ocFoKLrmPydKQVAM1ARaC/36W0RCivBEWnB4YHqbD8G/ttC+0xJw4FhdgvEu0mHCi0rxSvFFenfDIgR0x/vEZ6lf21XyGDwLZ2NZ4OVSawAQTpBJmkvz4hRHEBP6P2Vn/Ib2iFCpFBol+o6060kpP5Q2Ty3mI9+jErfRyHts+sgHXI9U/FyExD5E+h8Sg2y1CtRhVgXOs+zLHTF4JHusr6WBk0riPrmVWvwOdyFRFpLiNEXJegMaKkWOHrKb+PhHytn7MYXAUlBRy++8g2ds7zj3o7yj1337TCVFwWxI3oBn50cetwnmtWB0Dfecrb+62W6pUaIrzncA3xvlJbk31QUDpV7EoS2NShHmhAoXmPrrUMT3CPmWIhxnsvkYpscbaLuY0xYxV1HNkLiLkqzd+WWA84pg4ucThhGg5HS3mEvF7cNZzUnRRNGju9VDg73KXN4HZoQzQAQWgesyNjd4EIaq6Mz2JQ3sNsI0tKzLBLFutCLpmy5xlOCQ98cO1rA7NUhN44Ldj9AYAp8NpN3AmOVB9Bpiqv5dYXZXf8oAsq6LwJ2/TFFbpXE2lsUWVMYFb3blDhYKBa2j1jGDXbe5OUSRVR7niQUCEVYa7TIaxKIGRyY0STqQcDfImI6SipYsQ4=
  on:
    tags: true
    repo: ufranske/jinja2_stringcase
    python: 2.7
